### ISSUE TITLE
Apart 2.0 throws exception

### ISSUE THREAD

**Issue by PoslavskySV** [F-Feng/APart#1]
Test case:

```
expr = (-128 a^2 - 112 a b - 248 a - 172 b + 90 c - 15)/(c ( a + c) (4 a + 2 b + 2 c + 1));
ApartAll[expr, {a, b, c}]
```

throws `Error: -128 a^2-112 b a-248 a-172 b+90 c-15 is not Linear Polynomial of {a,b,c}`. With the previous version of Apart everything is ok:

```
$Apart[expr, {a, b, c}]
```

gives 

```
-248 ($ApartIR[1/(
  c (1 + 4 a + 2 b + 2 c)), {a, b, c}, {c,
  1 + 4 a + 2 b + 2 c}, {-1, -1}] - $ApartIR[
  1/((a + c) (1 + 4 a + 2 b + 2 c)), {a, b, c}, {a + c,
    1 + 4 a + 2 b + 2 c}, {-1, -1}]) +
    90 $ApartIR[
      1/((a + c) (1 + 4 a + 2 b + 2 c)), {a, b, c}, {a + c,
        1 + 4 a + 2 b + 2 c}, {-1, -1}] -
    128 ($ApartIR[a/(
      c (1 + 4 a + 2 b + 2 c)), {a, b, c}, {a, c,
      1 + 4 a + 2 b + 2 c}, {1, -1, -1}] - $ApartIR[
      a/((a + c) (1 + 4 a + 2 b + 2 c)), {a, b, c}, {a, a + c,
        1 + 4 a + 2 b + 2 c}, {1, -1, -1}]) -
    112 ($ApartIR[b/(
      c (1 + 4 a + 2 b + 2 c)), {a, b, c}, {b, c,
      1 + 4 a + 2 b + 2 c}, {1, -1, -1}] - $ApartIR[
      b/((a + c) (1 + 4 a + 2 b + 2 c)), {a, b, c}, {b, a + c,
        1 + 4 a + 2 b + 2 c}, {1, -1, -1}]) -
    172 (1/2 $ApartIR[1/(c (a + c)), {a, b, c}, {c, a + c}, {-1, -1}] -
        2 $ApartIR[1/(
          c (1 + 4 a + 2 b + 2 c)), {a, b, c}, {c,
          1 + 4 a + 2 b + 2 c}, {-1, -1}] + $ApartIR[
      1/((a + c) (1 + 4 a + 2 b + 2 c)), {a, b, c}, {a + c,
        1 + 4 a + 2 b + 2 c}, {-1, -1}] -
        1/2 $ApartIR[1/(
          c (a + c) (1 + 4 a + 2 b + 2 c)), {a, b, c}, {c, a + c,
          1 + 4 a + 2 b + 2 c}, {-1, -1, -1}]) -
    15 $ApartIR[1/(
      c (a + c) (1 + 4 a + 2 b + 2 c)), {a, b, c}, {c, a + c,
      1 + 4 a + 2 b + 2 c}, {-1, -1, -1}]
```

**Comment by F-Feng** [comment]
Hi Poslavsky, Thanks for the feedback!

Yes, you are right, the Apart2 will show an error message when you apply ApartAll directly to your expression. And actually, I prefer to take that as a new feather in Apart2, since sometimes, we want to take the whole linear numerator as a single item, which means it will not automatically expand the numerator within the Apart2.

Anyway, you can use the following ApartAll2, which is defined as follows:

ApartAll2[exp_, vars_] := Module[{tmp, VF},
  tmp = Distribute[VF[Expand[exp, Alternatives @@ vars]]];
  tmp = tmp /. VF[ex_] :> ApartAll[ex, vars];
  Return[tmp];
  ]

expr = (-128 a^2 - 112 a b - 248 a - 172 b + 90 c - 15)/(c ( a + c) (4 a + 2 b + 2 c + 1));
ApartAll2[expr, {a, b, c}]

![apart](https://cloud.githubusercontent.com/assets/8832209/15471054/8847aaba-2126-11e6-83f8-2275ce2b8e03.png)

**Comment by PoslavskySV** [comment]
Great! Many thanks!
